project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Trevor Kapuvari Python Demonstrations"
  site-url: "https://Quarto-Python-Website/quarto-website-starter" 
  repo-url: https://Quarto-Python-Website/quarto-website-starter 
  repo-actions: [source]

  page-footer:
    right: "This page is built with 1s and 0s and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Trevor Kapuvari, 2024"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/trevor-kapuvari/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/TrevorKap
        text: "GitHub Profile"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/Assignment2Kapuvari.ipynb
          - analysis/assignment-5.ipynb
          - analysis/evictions.ipynb
          - analysis/predictionmodelling.ipynb
          - analysis/streetsandwebscrap.ipynb
          - analysis/RFvsSKL.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




