project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Trevor Kapuvari Python Demonstrations"
  site-url: "https://github.com/TrevorKap/Quarto-Python-Website" 
  repo-url: https://github.com/TrevorKap/Quarto-Python-Website
  repo-actions: [source]

  page-footer:
    right: "This page is built with 1s and 0s and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Trevor Kapuvari, 2024"

  sidebar:
    logo: "images/Python.png"
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/trevor-kapuvari/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/TrevorKap
        text: "GitHub Profile"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/Assignment2Kapuvari.ipynb
          - analysis/assignment-5.ipynb
          - analysis/evictions.ipynb
          - analysis/predictionmodelling.ipynb
          - analysis/streetsandwebscrap.ipynb
          - analysis/RFvsSKL.ipynb
      - section: RemoteSensing/index.qmd
        contents:
          - RemoteSensing/national_landcover_supervised_classification.ipynb
          - RemoteSensing/land_surface_temperature.ipynb
          - RemoteSensing/national_landcover_supervised_classification.ipynb
      - section: SpatialOptimization/index.qmd
        contents:
          - SpatialOptimization/pdispersion.py
          - SpatialOptimization/p_median_with_pulp.ipynb
          - SpatialOptimization/Knapsack_Example.ipynb
          - SpatialOptimization/CoverageMatrix.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




